services:
  azit:
    build:
      context: .
      target: jre
    ports:
      - 8080:8080
    depends_on:
      azit-database:
        condition: service_healthy
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./volumes/${UPLOADS_DIR:-uploads}/:/app/uploads
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "8080"]
      interval: 5s
      timeout: 5s
      retries: 12
      start_period: 5s
    networks:
      - azit-net
    develop:
      watch:
        - action: rebuild
          path: ./src/
        - action: rebuild
          path: ./pom.xml
    profiles:
      - prod

  azit-backend:
    build:
      context: .
      target: maven
    ports:
      - 8080:8080
    depends_on:
      azit-database:
        condition: service_healthy
      azit-frontend:
        condition: service_started
    volumes:
      - ./volumes/${UPLOADS_DIR:-uploads}/:/app/uploads
      - azit-resources-dist:/app/target/classes/
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    networks:
      - azit-net
    develop:
      watch:
        - action: sync+exec
          path: ./src/main/java/
          target: /app/src/main/java/
          exec:
            working_dir: /app
            command: ./mvnw compile
    profiles:
      - dev

  azit-frontend:
    build:
      context: .
      target: vite
    volumes:
      - azit-resources-dist:/app/target/classes/
    networks:
      - azit-net
    command:
    develop:
      watch:
        - action: sync
          path: ./src/main/resources/
          target: /app/src/main/resources/
    profiles:
      - dev

  azit-database:
    image: mysql:8
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: azit_db
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - ./volumes/${DB_DIR:-db}/:/var/lib/mysql
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "${DB_USER}",
          "-p${DB_PASSWORD}",
        ]
      interval: 5s
      timeout: 5s
      start_period: 5s
      retries: 12
    networks:
      - azit-net
    profiles:
      - prod
      - dev

networks:
  azit-net:
